modLoader="javafml"
loaderVersion="[47,)"   # Forge 1.20.x
license="MIT"
issueTrackerURL="https://example.com/issues"

[[mods]]
modId="vsyncmod"
version="1.0.0"
displayName="Vsync Mod"
description='''This mod adds custom weapons with Epic Fight support.'''
logoFile="assets/vsyncmod/icon.png"
authors="ShibaMx"
